### ISSUE TITLE
Package name conflicts on Ubuntu

### ISSUE THREAD

**Issue by sudosubin** [barnumbirr/delta-debian#1]
### Issue
There is a `delta` named package in Ubuntu official repository already.

The `delta-debian` package was installed and working great, but `apt update && apt upgrade` make it wrong. System automatically overrides preinstalled `delta` with new one.

I think changing the package name from `delta` to `git-delta` or `delta-diff` will be great for Ubuntu based distros.

- [ubuntu delta package](https://packages.ubuntu.com/focal/delta)

### System Information
- Kbuntu 20.04 LTS
- latest release of delta (`v0.1.1-1`)

### Terminal Output
- Update search
![image](https://user-images.githubusercontent.com/32478597/83947727-cfc88b80-a853-11ea-8d69-fe013098a2f5.png)

**Comment by barnumbirr** [comment]
Hello,

you're absolutely right! I seem to have missed that. I'll try and publish a new version of the package, with correct name in the next couple of days.

Thank you for the feedback.

Cheers.

**Comment by sudosubin** [comment]
Really thank you for the fast response.

If there is anything I can do to help, please mention me :pray: 

Thank you!

**Comment by barnumbirr** [comment]
Thanks, I'll keep that in mind 👌
I'll ping you once the next release is up.

**Comment by barnumbirr** [comment]
@sudosubin Issue should be fixed (if the build passes :see_no_evil: )
Thanks again for reporting this.

**Comment by sudosubin** [comment]
Yes, new version (`v0.1.1-2`) now works well.
Thanks! :slightly_smiling_face:
